/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Sun Sep 03 17:37:38 2017. */

#include "include\unionproto.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const bool ConnectionCallbackMessage_sucess_default = false;
const char ConnectionCallbackMessage_motd_default[128] = "";
const int32_t ConnectionCallbackMessage_mapId_default = 0;
const int32_t ConnectionCallbackMessage_clientId_default = 0;
const char ConnectionMessage_name_default[16] = "";
const int32_t GameDataMessage_GameMode_default = 0;
const int32_t GameDataMessage_playersCount_default = 0;
const int32_t SDL_Rect_x_default = 0;
const int32_t SDL_Rect_y_default = 0;
const int32_t SDL_Rect_h_default = 0;
const int32_t SDL_Rect_w_default = 0;
const char Player_name_default[16] = "";
const int32_t Player_id_default = 0;
const bool Player_calibred_default = false;
const int32_t Player_health_default = 0;
const int32_t Player_ammo_default = 0;
const int32_t Player_step_default = 0;
const bool Player_fire_default = false;
const bool Player_walk_default = false;
const int32_t Player_state_default = 0;
const int32_t Player_lastAnim_default = 0;
const int32_t Player_fireIdle_default = 0;
const int32_t BulletMessage_id_default = 0;
const int32_t BulletMessage_ownerId_default = 0;


const pb_field_t ConnectionCallbackMessage_fields[5] = {
	PB_FIELD(1, BOOL    , REQUIRED, STATIC  , FIRST, ConnectionCallbackMessage, sucess, sucess, &ConnectionCallbackMessage_sucess_default),
	PB_FIELD(2, STRING  , REQUIRED, STATIC  , OTHER, ConnectionCallbackMessage, motd, sucess, &ConnectionCallbackMessage_motd_default),
	PB_FIELD(3, INT32   , REQUIRED, STATIC  , OTHER, ConnectionCallbackMessage, mapId, motd, &ConnectionCallbackMessage_mapId_default),
	PB_FIELD(4, INT32   , REQUIRED, STATIC  , OTHER, ConnectionCallbackMessage, clientId, mapId, &ConnectionCallbackMessage_clientId_default),
	PB_LAST_FIELD
};

const pb_field_t ConnectionMessage_fields[2] = {
	PB_FIELD(2, STRING  , REQUIRED, STATIC  , FIRST, ConnectionMessage, name, name, &ConnectionMessage_name_default),
	PB_LAST_FIELD
};

const pb_field_t GameDataMessage_fields[5] = {
	PB_FIELD(1, INT32   , REQUIRED, STATIC  , FIRST, GameDataMessage, GameMode, GameMode, &GameDataMessage_GameMode_default),
	PB_FIELD(2, INT32   , REQUIRED, STATIC  , OTHER, GameDataMessage, playersCount, GameMode, &GameDataMessage_playersCount_default),
	PB_FIELD(3, MESSAGE , REPEATED, CALLBACK, OTHER, GameDataMessage, players, playersCount, &Player_fields),
	PB_FIELD(4, MESSAGE , REPEATED, CALLBACK, OTHER, GameDataMessage, bullets, players, &BulletMessage_fields),
	PB_LAST_FIELD
};

const pb_field_t SDL_Rect_fields[5] = {
	PB_FIELD(1, INT32   , REQUIRED, STATIC  , FIRST, SDL_Rect, x, x, &SDL_Rect_x_default),
	PB_FIELD(2, INT32   , REQUIRED, STATIC  , OTHER, SDL_Rect, y, x, &SDL_Rect_y_default),
	PB_FIELD(3, INT32   , REQUIRED, STATIC  , OTHER, SDL_Rect, h, y, &SDL_Rect_h_default),
	PB_FIELD(4, INT32   , REQUIRED, STATIC  , OTHER, SDL_Rect, w, h, &SDL_Rect_w_default),
	PB_LAST_FIELD
};

const pb_field_t Player_fields[14] = {
	PB_FIELD(1, STRING  , REQUIRED, STATIC  , FIRST, Player, name, name, &Player_name_default),
	PB_FIELD(2, INT32   , REQUIRED, STATIC  , OTHER, Player, id, name, &Player_id_default),
	PB_FIELD(4, BOOL    , REQUIRED, STATIC  , OTHER, Player, calibred, id, &Player_calibred_default),
	PB_FIELD(5, INT32   , REQUIRED, STATIC  , OTHER, Player, health, calibred, &Player_health_default),
	PB_FIELD(6, INT32   , REQUIRED, STATIC  , OTHER, Player, ammo, health, &Player_ammo_default),
	PB_FIELD(7, INT32   , REQUIRED, STATIC  , OTHER, Player, step, ammo, &Player_step_default),
	PB_FIELD(8, BOOL    , REQUIRED, STATIC  , OTHER, Player, fire, step, &Player_fire_default),
	PB_FIELD(9, BOOL    , REQUIRED, STATIC  , OTHER, Player, walk, fire, &Player_walk_default),
	PB_FIELD(10, INT32   , REQUIRED, STATIC  , OTHER, Player, state, walk, &Player_state_default),
	PB_FIELD(11, INT32   , REQUIRED, STATIC  , OTHER, Player, lastAnim, state, &Player_lastAnim_default),
	PB_FIELD(12, INT32   , REQUIRED, STATIC  , OTHER, Player, fireIdle, lastAnim, &Player_fireIdle_default),
	PB_FIELD(13, MESSAGE , REQUIRED, STATIC  , OTHER, Player, Pos, fireIdle, &SDL_Rect_fields),
	PB_FIELD(14, MESSAGE , REQUIRED, STATIC  , OTHER, Player, sprite, Pos, &SDL_Rect_fields),
	PB_LAST_FIELD
};

const pb_field_t BulletMessage_fields[5] = {
	PB_FIELD(1, INT32   , REQUIRED, STATIC  , FIRST, BulletMessage, id, id, &BulletMessage_id_default),
	PB_FIELD(2, INT32   , REQUIRED, STATIC  , OTHER, BulletMessage, ownerId, id, &BulletMessage_ownerId_default),
	PB_FIELD(3, MESSAGE , REQUIRED, STATIC  , OTHER, BulletMessage, pos, ownerId, &SDL_Rect_fields),
	PB_FIELD(4, MESSAGE , REQUIRED, STATIC  , OTHER, BulletMessage, dest, pos, &SDL_Rect_fields),
	PB_LAST_FIELD
};

const pb_field_t UnionMessage_fields[6] = {
	PB_FIELD(1, MESSAGE , OPTIONAL, STATIC  , FIRST, UnionMessage, connCallbackMessage, connCallbackMessage, &ConnectionMessage_fields),
	PB_FIELD(2, MESSAGE , OPTIONAL, STATIC  , OTHER, UnionMessage, connMessage, connCallbackMessage, &ConnectionCallbackMessage_fields),
	PB_FIELD(3, MESSAGE , OPTIONAL, STATIC  , OTHER, UnionMessage, bulletMessage, connMessage, &BulletMessage_fields),
	PB_FIELD(4, MESSAGE , OPTIONAL, STATIC  , OTHER, UnionMessage, gameData, bulletMessage, &GameDataMessage_fields),
	PB_FIELD(5, MESSAGE , OPTIONAL, STATIC  , OTHER, UnionMessage, playerMessage, gameData, &Player_fields),
	PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
* compile-time option. You can do that in pb.h or on compiler command line.
*
* The reason you need to do this is that some of your messages contain tag
* numbers or field sizes that are larger than what can fit in 8 or 16 bit
* field descriptors.
*/
PB_STATIC_ASSERT((pb_membersize(Player, Pos) < 65536 && pb_membersize(Player, sprite) < 65536 && pb_membersize(BulletMessage, pos) < 65536 && pb_membersize(BulletMessage, dest) < 65536 && pb_membersize(UnionMessage, connCallbackMessage) < 65536 && pb_membersize(UnionMessage, connMessage) < 65536 && pb_membersize(UnionMessage, bulletMessage) < 65536 && pb_membersize(UnionMessage, gameData) < 65536 && pb_membersize(UnionMessage, playerMessage) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_ConnectionCallbackMessage_ConnectionMessage_GameDataMessage_SDL_Rect_Player_BulletMessage_UnionMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
	/* If you get an error here, it means that you need to define PB_FIELD_16BIT
	* compile-time option. You can do that in pb.h or on compiler command line.
	*
	* The reason you need to do this is that some of your messages contain tag
	* numbers or field sizes that are larger than what can fit in the default
	* 8 bit descriptors.
	*/
	PB_STATIC_ASSERT((pb_membersize(Player, Pos) < 256 && pb_membersize(Player, sprite) < 256 && pb_membersize(BulletMessage, pos) < 256 && pb_membersize(BulletMessage, dest) < 256 && pb_membersize(UnionMessage, connCallbackMessage) < 256 && pb_membersize(UnionMessage, connMessage) < 256 && pb_membersize(UnionMessage, bulletMessage) < 256 && pb_membersize(UnionMessage, gameData) < 256 && pb_membersize(UnionMessage, playerMessage) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_ConnectionCallbackMessage_ConnectionMessage_GameDataMessage_SDL_Rect_Player_BulletMessage_UnionMessage)
#endif
	/* @@protoc_insertion_point(eof) */
