/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Tue Oct 10 13:30:04 2017. */

#include "include\unionproto.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ConnectionCallbackMessage_fields[5] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, ConnectionCallbackMessage, sucess, sucess, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, ConnectionCallbackMessage, motd, sucess, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, ConnectionCallbackMessage, map, motd, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, ConnectionCallbackMessage, clientId, map, 0),
    PB_LAST_FIELD
};

const pb_field_t ConnectionMessage_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, ConnectionMessage, name, name, 0),
    PB_LAST_FIELD
};

const pb_field_t SpawnMessage_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SpawnMessage, id, id, 0),
    PB_LAST_FIELD
};

const pb_field_t SpawnCallbackMessage_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SpawnCallbackMessage, id, id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, SpawnCallbackMessage, x, id, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, SpawnCallbackMessage, y, x, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, SpawnCallbackMessage, health, y, 0),
    PB_LAST_FIELD
};

const pb_field_t GameDataMessage_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, GameDataMessage, gameMode, gameMode, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, GameDataMessage, playersCount, gameMode, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, GameDataMessage, players, playersCount, &Player_fields),
    PB_FIELD(  4, MESSAGE , REPEATED, CALLBACK, OTHER, GameDataMessage, bullets, players, &BulletMessage_fields),
    PB_LAST_FIELD
};

const pb_field_t SDL_Rect_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SDL_Rect, x, x, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, SDL_Rect, y, x, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, SDL_Rect, h, y, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, SDL_Rect, w, h, 0),
    PB_LAST_FIELD
};

const pb_field_t PlayerBase_fields[7] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, PlayerBase, id, id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, PlayerBase, health, id, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, PlayerBase, ammo, health, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, PlayerBase, state, ammo, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, PlayerBase, orientation, state, 0),
    PB_FIELD(  6, MESSAGE , REQUIRED, STATIC  , OTHER, PlayerBase, pos, orientation, &SDL_Rect_fields),
    PB_LAST_FIELD
};

const pb_field_t Player_fields[7] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, Player, playerBase, playerBase, &PlayerBase_fields),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, Player, lastAnim, playerBase, 0),
    PB_FIELD(  3, MESSAGE , REQUIRED, STATIC  , OTHER, Player, sprite, lastAnim, &SDL_Rect_fields),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, Player, walkAnimationStep, sprite, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, Player, deathAnimationStep, walkAnimationStep, 0),
    PB_FIELD(  6, STRING  , REQUIRED, STATIC  , OTHER, Player, name, deathAnimationStep, 0),
    PB_LAST_FIELD
};

const pb_field_t BulletMessage_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, BulletMessage, id, id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, BulletMessage, state, id, 0),
    PB_FIELD(  3, MESSAGE , REQUIRED, STATIC  , OTHER, BulletMessage, pos, state, &SDL_Rect_fields),
    PB_FIELD(  4, MESSAGE , REQUIRED, STATIC  , OTHER, BulletMessage, dest, pos, &SDL_Rect_fields),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, BulletMessage, ownerId, dest, 0),
    PB_LAST_FIELD
};

const pb_field_t UnionMessage_fields[8] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, UnionMessage, connCallbackMessage, connCallbackMessage, &ConnectionMessage_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, UnionMessage, connMessage, connCallbackMessage, &ConnectionCallbackMessage_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, UnionMessage, bulletMessage, connMessage, &BulletMessage_fields),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, UnionMessage, playerMessage, bulletMessage, &PlayerBase_fields),
    PB_FIELD(  5, MESSAGE , OPTIONAL, STATIC  , OTHER, UnionMessage, spawnMessage, playerMessage, &SpawnMessage_fields),
    PB_FIELD(  6, MESSAGE , OPTIONAL, STATIC  , OTHER, UnionMessage, spawnCallbackMessage, spawnMessage, &SpawnCallbackMessage_fields),
    PB_FIELD(  7, MESSAGE , OPTIONAL, STATIC  , OTHER, UnionMessage, gameDataMessage, spawnCallbackMessage, &GameDataMessage_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(PlayerBase, pos) < 65536 && pb_membersize(Player, playerBase) < 65536 && pb_membersize(Player, sprite) < 65536 && pb_membersize(BulletMessage, pos) < 65536 && pb_membersize(BulletMessage, dest) < 65536 && pb_membersize(UnionMessage, connCallbackMessage) < 65536 && pb_membersize(UnionMessage, connMessage) < 65536 && pb_membersize(UnionMessage, bulletMessage) < 65536 && pb_membersize(UnionMessage, playerMessage) < 65536 && pb_membersize(UnionMessage, spawnMessage) < 65536 && pb_membersize(UnionMessage, spawnCallbackMessage) < 65536 && pb_membersize(UnionMessage, gameDataMessage) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_ConnectionCallbackMessage_ConnectionMessage_SpawnMessage_SpawnCallbackMessage_GameDataMessage_SDL_Rect_PlayerBase_Player_BulletMessage_UnionMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(PlayerBase, pos) < 256 && pb_membersize(Player, playerBase) < 256 && pb_membersize(Player, sprite) < 256 && pb_membersize(BulletMessage, pos) < 256 && pb_membersize(BulletMessage, dest) < 256 && pb_membersize(UnionMessage, connCallbackMessage) < 256 && pb_membersize(UnionMessage, connMessage) < 256 && pb_membersize(UnionMessage, bulletMessage) < 256 && pb_membersize(UnionMessage, playerMessage) < 256 && pb_membersize(UnionMessage, spawnMessage) < 256 && pb_membersize(UnionMessage, spawnCallbackMessage) < 256 && pb_membersize(UnionMessage, gameDataMessage) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_ConnectionCallbackMessage_ConnectionMessage_SpawnMessage_SpawnCallbackMessage_GameDataMessage_SDL_Rect_PlayerBase_Player_BulletMessage_UnionMessage)
#endif


/* @@protoc_insertion_point(eof) */