/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Tue Aug 29 21:23:25 2017. */

#ifndef PB_UNIONPROTO_PB_H_INCLUDED
#define PB_UNIONPROTO_PB_H_INCLUDED
#include "pb.h"
#include <SDL.h>
/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

	/* Struct definitions */
	typedef struct _ConnectionCallbackMessage {
		bool sucess;
		char motd[128];
		int32_t mapId;
		int32_t clientId;
		/* @@protoc_insertion_point(struct:ConnectionCallbackMessage) */
	} ConnectionCallbackMessage;

	typedef struct _ConnectionMessage {
		char name[16];
		/* @@protoc_insertion_point(struct:ConnectionMessage) */
	} ConnectionMessage;

	typedef struct _GameDataMessage {
		int32_t GameMode;
		int32_t playersCount;
		pb_callback_t players;
		/* @@protoc_insertion_point(struct:GameDataMessage) */
	} GameDataMessage;

	typedef struct _BulletMessage {
		SDL_Rect Pos;
		/* @@protoc_insertion_point(struct:BulletMessage) */
	} BulletMessage;

	typedef struct _Player {
		char name[16];
		int32_t id;
		pb_callback_t bullets;
		bool calibred;
		int32_t health;
		int32_t ammo;
		int32_t step;
		bool fire;
		bool walk;
		int32_t state;
		int32_t lastAnim;
		int32_t fireIdle;
		SDL_Rect Pos;
		SDL_Rect sprite;
		/* @@protoc_insertion_point(struct:Player) */
	} Player;

	typedef struct _UnionMessage {
		bool has_connCallbackMessage;
		ConnectionMessage connCallbackMessage;
		bool has_connMessage;
		ConnectionCallbackMessage connMessage;
		bool has_bulletMessage;
		BulletMessage bulletMessage;
		bool has_gameData;
		GameDataMessage gameData;
		bool has_playerMessage;
		Player playerMessage;
		/* @@protoc_insertion_point(struct:UnionMessage) */
	} UnionMessage;

	/* Default values for struct fields */
	extern const bool ConnectionCallbackMessage_sucess_default;
	extern const char ConnectionCallbackMessage_motd_default[128];
	extern const int32_t ConnectionCallbackMessage_mapId_default;
	extern const int32_t ConnectionCallbackMessage_clientId_default;
	extern const char ConnectionMessage_name_default[16];
	extern const int32_t GameDataMessage_GameMode_default;
	extern const int32_t GameDataMessage_playersCount_default;
	extern const int32_t SDL_Rect_x_default;
	extern const int32_t SDL_Rect_y_default;
	extern const int32_t SDL_Rect_h_default;
	extern const int32_t SDL_Rect_w_default;
	extern const char Player_name_default[16];
	extern const int32_t Player_id_default;
	extern const bool Player_calibred_default;
	extern const int32_t Player_health_default;
	extern const int32_t Player_ammo_default;
	extern const int32_t Player_step_default;
	extern const bool Player_fire_default;
	extern const bool Player_walk_default;
	extern const int32_t Player_state_default;
	extern const int32_t Player_lastAnim_default;
	extern const int32_t Player_fireIdle_default;

	/* Initializer values for message structs */
#define ConnectionCallbackMessage_init_default   {false, "", 0, 0}
#define ConnectionMessage_init_default           {""}
#define GameDataMessage_init_default             {0, 0, {{NULL}, NULL}}
#define SDL_Rect_init_default                    {0, 0, 0, 0}
#define Player_init_default                      {"", 0, {{NULL}, NULL}, false, 0, 0, 0, false, false, 0, 0, 0, SDL_Rect_init_default, SDL_Rect_init_default}
#define BulletMessage_init_default               {SDL_Rect_init_default}
#define UnionMessage_init_default                {false, ConnectionMessage_init_default, false, ConnectionCallbackMessage_init_default, false, BulletMessage_init_default, false, GameDataMessage_init_default, false, Player_init_default}
#define ConnectionCallbackMessage_init_zero      {0, "", 0, 0}
#define ConnectionMessage_init_zero              {""}
#define GameDataMessage_init_zero                {0, 0, {{NULL}, NULL}}
#define SDL_Rect_init_zero                       {0, 0, 0, 0}
#define Player_init_zero                         {"", 0, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0, 0, 0, 0, SDL_Rect_init_zero, SDL_Rect_init_zero}
#define BulletMessage_init_zero                  {SDL_Rect_init_zero}
#define UnionMessage_init_zero                   {false, ConnectionMessage_init_zero, false, ConnectionCallbackMessage_init_zero, false, BulletMessage_init_zero, false, GameDataMessage_init_zero, false, Player_init_zero}

	/* Field tags (for use in manual encoding/decoding) */
#define ConnectionCallbackMessage_sucess_tag     1
#define ConnectionCallbackMessage_motd_tag       2
#define ConnectionCallbackMessage_mapId_tag      3
#define ConnectionCallbackMessage_clientId_tag   4
#define ConnectionMessage_name_tag               2
#define GameDataMessage_GameMode_tag             1
#define GameDataMessage_playersCount_tag         2
#define GameDataMessage_players_tag              3
#define SDL_Rect_x_tag                           1
#define SDL_Rect_y_tag                           2
#define SDL_Rect_h_tag                           3
#define SDL_Rect_w_tag                           4
#define BulletMessage_Pos_tag                    1
#define Player_name_tag                          1
#define Player_id_tag                            2
#define Player_bullets_tag                       3
#define Player_calibred_tag                      4
#define Player_health_tag                        5
#define Player_ammo_tag                          6
#define Player_step_tag                          7
#define Player_fire_tag                          8
#define Player_walk_tag                          9
#define Player_state_tag                         10
#define Player_lastAnim_tag                      11
#define Player_fireIdle_tag                      12
#define Player_Pos_tag                           13
#define Player_sprite_tag                        14
#define UnionMessage_connCallbackMessage_tag     1
#define UnionMessage_connMessage_tag             2
#define UnionMessage_bulletMessage_tag           3
#define UnionMessage_gameData_tag                4
#define UnionMessage_playerMessage_tag           5

	/* Struct field encoding specification for nanopb */
	extern const pb_field_t ConnectionCallbackMessage_fields[5];
	extern const pb_field_t ConnectionMessage_fields[2];
	extern const pb_field_t GameDataMessage_fields[4];
	extern const pb_field_t SDL_Rect_fields[5];
	extern const pb_field_t Player_fields[15];
	extern const pb_field_t BulletMessage_fields[2];
	extern const pb_field_t UnionMessage_fields[6];

	/* Maximum encoded size of messages (where known) */
#define ConnectionCallbackMessage_size           155
#define ConnectionMessage_size                   18
	/* GameDataMessage_size depends on runtime parameters */
#define SDL_Rect_size                            44
	/* Player_size depends on runtime parameters */
#define BulletMessage_size                       46
#define UnionMessage_size                        (238 + GameDataMessage_size + Player_size)

	/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define UNIONPROTO_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
  /* @@protoc_insertion_point(eof) */

#endif
