# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

stages:
    - build
    
before_script:
    - sudo apt update && sudo apt -y install build-essential libsdl2-image-dev libsdl2-dev libsdl2-ttf-dev
    - gcc -v
    - cd Client
    - make distclean
after_script:
    - make distclean


build-client:
  stage: build
  script: 
    - make
  only:
    - master

build-server:
  stage: build
  script: 
    - make
  only:
    - master